### ISSUE TITLE
Accessibility statement

### ISSUE THREAD

**Issue by skade** [RustFestEU/2017.rustfest.eu#36]
Clarified the points for the statement. We have:

- non-gendered toilets
- wheelchair accessible venue and toilets (this changed)
- a quiet room, wheelchair accessible (this changed, too)
- no-scent policy

We cannot guarantee transcription currently.

**Comment by listochkin** [comment]
Toilets _are_ gendered at the venue

**Comment by Hoverbear** [comment]
http://2017.rustfest.eu/accessibility/ has been posted
